name: mule-secret-encryption-tool

on:
  workflow_dispatch:
    inputs:
      secret-1:
        description: 'Secret 1'
        type: string
      secret-2:
        description: 'Secret 2'
        type: string
      secret-3:
        description: 'Secret 3'
        type: string
      secret-4:
        description: 'Secret 4'
        type: string
      secret-5:
        description: 'Secret 5'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  encrypt-secrets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script 
        run: |
          chmod +x encrypt.sh; 
          ./encrypt.sh \
          ${{ github.event.inputs.secret-1 }} \
          ${{ github.event.inputs.secret-2 }} \
          ${{ github.event.inputs.secret-3 }} \
          ${{ github.event.inputs.secret-4 }} \
          ${{ github.event.inputs.secret-5 }}
