name: encrypt-prod

on:
  workflow_dispatch:
    inputs:
      secret-1:
        description: 'Secret 1'
        type: string
      secret-2:
        description: 'Secret 2'
        type: string
      secret-3:
        description: 'Secret 3'
        type: string
      secret-4:
        description: 'Secret 4'
        type: string
      secret-5:
        description: 'Secret 5'
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  encrypt-secrets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Execute encryption script
        run: |
          chmod +x encrypt.sh; 
          SECRET1=${{ github.event.inputs.secret-1 }};
          SECRET1=${SECRET1:-blank};
          SECRET2=${{ github.event.inputs.secret-2 }};
          SECRET2=${SECRET2:-blank};
          SECRET3=${{ github.event.inputs.secret-3 }};
          SECRET3=${SECRET3:-blank};
          SECRET4=${{ github.event.inputs.secret-4 }};
          SECRET4=${SECRET4:-blank};
          SECRET5=${{ github.event.inputs.secret-5 }};
          SECRET5=${SECRET5:-blank};

          
          ./encrypt.sh \
          ${{ secrets.ENCRYPTION_KEY }} $SECRET1 $SECRET2 $SECRET3 $SECRET4 $SECRET5
