name: encrypt-all

on:
  workflow_dispatch:
    inputs:
      # NOTE: this input has the name WEBHOOK_TOKEN because this variable name is automatically masked by GH Actions.
      # The add-mask function cannot be used because it still results in the plaintext value being written to the log.
      # See here for further details: https://github.com/actions/runner/issues/475
      WEBHOOK_TOKEN:
        description: 'Secret in plain-text'
        type: string

jobs:
  encrypt-secret:
    runs-on: ubuntu-latest
    env:
      JAR_URL: 'https://docs.mulesoft.com/mule-runtime/4.4/_attachments/secure-properties-tool.jar'

    steps:

      #- name: Set environment variable which holds plaintext secret
        #run: |
          #echo '::echo::off'
          #stopMarker=$(uuidgen)
          #echo "::stop-commands::$stopMarker"
          #echo "plaintext_secret=${{ github.event.inputs.secret }}" >> $GITHUB_ENV
          #echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
          #echo "::$stopMarker::"
          #echo '::echo::on'
      
      #- name: Add mask
      #  run:  |
      #    stopMarker=$(uuidgen)
      #    echo "::stop-commands::$stopMarker"
      #    echo "::add-mask::${{ env.plaintext_secret }}"
      #    echo "::$stopMarker::"
        
      - name: Download encryption tool
        run: |
          echo "Downloading secure-properties-tool.jar from MuleSoft website..."
          curl -s $JAR_URL -o secure-properties-tool.jar
          chmod +x secure-properties-tool.jar
      
      - name: Encrypt secret
        env:
          PLAINTEXT_SECRET: ${{ github.event.inputs.WEBHOOK_TOKEN }}
        run: |
          #PLAINTEXT_SECRET=${{ github.event.inputs.WEBHOOK_TOKEN }}         
          ENCRYPTION_KEY_LOCAL=${{ secrets.ENCRYPTION_KEY_LOCAL }}
          ENCRYPTION_KEY_NONPROD=${{ secrets.ENCRYPTION_KEY_NONPROD }}
          ENCRYPTION_KEY_PROD=${{ secrets.ENCRYPTION_KEY_PROD }}
          LOCAL_ENCRYPTED_SECRET=$(java -cp secure-properties-tool.jar com.mulesoft.tools.SecurePropertiesTool string encrypt AES CBC $ENCRYPTION_KEY_LOCAL $PLAINTEXT_SECRET)
          NONPROD_ENCRYPTED_SECRET=$(java -cp secure-properties-tool.jar com.mulesoft.tools.SecurePropertiesTool string encrypt AES CBC $ENCRYPTION_KEY_NONPROD $PLAINTEXT_SECRET)
          PROD_ENCRYPTED_SECRET=$(java -cp secure-properties-tool.jar com.mulesoft.tools.SecurePropertiesTool string encrypt AES CBC $ENCRYPTION_KEY_PROD $PLAINTEXT_SECRET)
          
          echo "Encrypted values"
          echo "---------------------------------------------------"
          echo "Local:    $LOCAL_ENCRYPTED_SECRET"
          echo "Non-Prod: $NONPROD_ENCRYPTED_SECRET"
          echo "Prod:     $PROD_ENCRYPTED_SECRET"
